dist: xenial
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
notifications:
  email: false
before_script:
  - git clone -b 1.39.19 https://github.com/emscripten-core/emsdk.git
  - cd emsdk
  - ./emsdk install 1.39.19
  - ./emsdk activate 1.39.19
  - source ./emsdk_env.sh
  - cd ..
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.emscripten_cache"
