name: CI

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: '3.1.13'
      - run: npm ci
      - run: npm test
      - name: 'Upload artifact'
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist

  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: dist
      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: dist
          force: false
          target-folder: preview/${{ github.event.number }}
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: dist
          force: false
          clean-exclude: |
            LICENSE.md
            preview
