name: Delete preview deployment

on:
  pull_request:
    types: [ closed ]
permissions:
  contents: write
jobs:
  delete-preview:
    name: Delete preview deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: rm -rf preview/${{ github.event.number }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Delete preview of #${{ github.event.number }}'
          branch: gh-pages
